### ISSUE TITLE
Augurk 3.0

### ISSUE THREAD

**Issue by jmezach** [Augurk/Augurk#79]
This issue describes the high level plan for Augurk 3.0 which we are currently working on. We'll use this to track progress on this big new release. The below list shows the big themes of this release, as well as the underlying work being done on that and branches in which those things are being developed. Each branch builds upon the previous one, meaning we'll have to take care in merging those into the feature/net-core-port branch. 

- [x] ~~Port to .NET Core so that Augurk can run cross-platform~~
  - [x] ~~Upgrade to RavenDB 4.0 (parent of #54)~~
  - [x] ~~Use ASP.NET Core's dependency injection (parent of #80)~~
  - [x] ~~Publishing and build pipeline fixes~~
  - [x] ~~Versioned API including Swagger docs (feature/api-versioning)~~
- [x] Improve test coverage (blocked by tonerdo/coverlet#342)
- [x] ~~Replace AngularJS with VueJS ui (feature/vuex-module-decorators)~~ (won't make it into 3.0)
- [x] Publish Docker image (feature/dockerize)
- [x] Merge with master

Items to test before releasing 3.0:
- [x] Feature expiration feature
- [x] Uploading product descriptions appears to be broken

parent of #40
parent of #81

**Comment by jmezach** [comment]
Augurk 3.0 has actually shipped in Q1 2019, but we haven't done much with it since then ;).
